name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Android Github Action
        uses: vukan-markovic/Github-Android-Action@1.2
            
