name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        run: flutter doctor

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --output build/flutter-build

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: build/flutter-build/app-release.apk
