name: Build Flutter APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle

      - name: Install Flutter 3.22.2
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # - name: Upload APK to GitHub Release
      #   if: github.ref == 'refs/heads/main'
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: build/app/outputs/flutter-apk/app-release.apk
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     tag: v1.${{ github.run_number }}
      #     name: Release v1.${{ github.run_number }}
      #     body: |
      #       This is an automated release of the Flutter APK built with Flutter 3.22.2.
      #       - Commit: ${{ github.sha }}
      #       - Built by: ${{ github.actor }}
